urls.py
from django.urls import path, include

from . import views

app_name = 'space'

urlpatterns = [
    path('', views.index, name='pagina-inicial'),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/<slug:action>/', views.categorias, name='manage-categoria'),
    path('categorias/<int:oid>/<slug:action>/', views.categorias, name='manage-categoria'),

    path('localizadores/', views.localizacoes, name='manage-localizador'),
    path('localizadores/<int:oid>/', views.localizacoes, name='manage-localizador'),

    path('espacos/', views.espacos, name='espacos'),
    path('espacos/<int:oid>/', views.espacos, name='espacos'),

    path('gestores/', views.gestores, name='gestores'),
    path('gestores/<slug:action>/', views.gestores, name='manage-gestores'),
    path('gestores/<int:oid>/<slug:action>/', views.gestores, name='manage-gestores'),

    path('reservas/', views.reservas, name='reservas'),
    path('reservas/<slug:action>/', views.reservas, name='manage-reservas'),

    path('json/', views.events, name='events')
]

templates/space/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Gestor de espaços{{titulo}}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap/4.1.3/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Full Calendar-->
    <link href="{% static 'css/fullcalendar/fullcalendar.min.css' %}" rel="stylesheet">

    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/jquery/3.3.1/jquery.min.js' %}"></script>
    <script src="{% static 'js/fullcalendar/fullcalendar.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'locale/pt-br.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>

    <!-- Timeline-Calendar -->
    <!--
    <link href='https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/scheduler.min.css' rel='stylesheet' />
    <script src='https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/scheduler.min.js'></script>
    -->

    <!-- Custom styles for this template -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <script>
        $(document).ready(function () {
            $('#calendar').fullCalendar({
                header: {
                    left: 'title',
                    right: 'today, month, agendaWeek, agendaDay, prev, next',
                },

                events: 'http://localhost:8000/space/json/',

                eventRender: function (event, element) {
                    element.attr('title', event.description);
                },

                eventClick: function (event) {
                    $(".modal-title").html(event.title + ' ' + event.id);
                    $('.modal-body').html(
                        '<strong>Objetivo:</strong><br>' +
                        event.description +
                        '<br><br>Inicio: ' + event.start.format('D/M/YYYY') +
                        '<br>Termino: ' + event.end.format('D/M/YYYY')
                    );
                    $("#form-modal").modal();
                },

                dayClick: function (date, event, view) {
                    $(".modal-title").html('Nova Reserva');
                    $.get("http://localhost:8000/space/reservas/create/?start=" + date.format('D/M/YYYY'),
                        function (data, status) {
                            $('.modal-body').html(data.result);
                            var $id_inicio_at = $("#id_inicio_at");
                            $id_inicio_at.mask('00/00/0000 00:00:00', {reverse: false});
                            var $id_termino_at = $("#id_termino_at");
                            $id_termino_at.mask('00/00/0000 00:00:00', {reverse: false});
                        });
                    $('form').attr('action', '/space/reservas/create/');
                    $("#form-modal").modal('show');

                }

            });
            $('#btn-fechar').click(function () {
                $('#calendar').fullCalendar('refetchEvents');
            });

            var $id_inicio_at = $("#id_inicio_at");
            $id_inicio_at.mask('00/00/0000 00:00:00', { reverse: false });

            var $id_termino_at = $("#id_termino_at");
            $id_termino_at.mask('00/00/0000 00:00:00', { reverse: false });
        });


    </script>
</head>

<body class="bg-light">

    {% block navbar %}
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <a class="navbar-brand mr-auto mr-lg-0" href="{% url 'space:pagina-inicial' %}"><img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1"
                alt="" class="mr-2 rounded"></a>
        <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'space:pagina-inicial' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'space:reservas' %}">Reservas</a>
                </li>
                <li class="nav-item">

                </li>
                <li class="nav-item">
                    <a href="#" data-toggle="modal" class="nav-link" data-target="#form-modal" data-action="create"
                        data-titulo="Reservar" data-url="{% url 'space:manage-reservas' 'create' %}">Soliciar</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">Administrar</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url 'space:categorias' %}">Categorias</a>
                        <a class="dropdown-item" href="{% url 'space:espacos' %}">Espaços Fisicos</a>
                        <a class="dropdown-item" href="{% url 'space:gestores' %}">Gestores</a>
                        <a class="dropdown-item" href="{% url 'space:manage-localizador' %}">Localização</a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'space:reservas' %}" class="dropdown-item">Reservas</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" method="POST">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="text" name="search" id="id_search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    {% endblock navbar %}

    {% block navbar_admin %}
    <div class="nav-scroller bg-white shadow-sm">
        <nav class="nav nav-underline">
            <a class="nav-link active" href="#">Dashboard</a>
            <a class="nav-link" href="#">
                Friends
                <span class="badge badge-pill bg-light align-text-bottom">27</span>
            </a>
            <a class="nav-link" href="#">Explore</a>
            <a class="nav-link" href="#">Suggestions</a>
            <a class="nav-link" href="#">Link</a>
            <a class="nav-link" href="#">Link</a>
            <a class="nav-link" href="#">Link</a>
            <a class="nav-link" href="#">Link</a>
            <a class="nav-link" href="#">Link</a>
        </nav>
    </div>
    {% endblock navbar_admin %}

    <main role="main" class="container">
        {% block container %}
        {% block header_page %}
        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
            <img class="mr-3" src="{% static 'img/bootstrap-outline.svg' %}" alt="" width="48" height="48">
            <div class="lh-100">
                <h6 class="mb-0 text-white lh-100">{{titulo}}</h6>
                <small>{{descricao}}</small>
            </div>
        </div>
        {% endblock header_page %}

        {% block content %}

        {% endblock content %}
        {% endblock container %}
    </main>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


    <script src="{% static 'js/bootstrap/4.1.3/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

    <script src="{% static 'js/m_ajax.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script>

    </script>
</body>

</html>

templates/space/index.html
{% extends 'space/base.html' %}
{% load space_extras %}

{% block navbar_admin %}{% endblock navbar_admin %}

{% block content %}

    {% if modulo %}
        {% include modulo|modulopage %}
    {% else %}
        <div id="calendar"></div>
    {% endif %}

    {% include 'space/componentes/includes/form_modal.html' %}
    
{% endblock content %}