urls.py
from django.urls import path, include

from . import views

app_name = 'space'

urlpatterns = [
    path('', views.index, name='pagina-inicial'),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/<slug:action>/', views.categorias, name='manage-categoria'),
    path('categorias/<int:oid>/<slug:action>/', views.categorias, name='manage-categoria'),

    path('localizadores/', views.localizacoes, name='manage-localizador'),
    path('localizadores/<int:oid>/', views.localizacoes, name='manage-localizador'),

    path('espacos/', views.espacos, name='espacos'),
    path('espacos/<int:oid>/', views.espacos, name='espacos'),

    path('gestores/', views.gestores, name='gestores'),
    path('gestores/<slug:action>/', views.gestores, name='manage-gestores'),
    path('gestores/<int:oid>/<slug:action>/', views.gestores, name='manage-gestores'),

    path('reservas/', views.reservas, name='reservas'),
    path('reservas/<slug:action>/', views.reservas, name='manage-reservas'),

    path('json/', views.events, name='events')
]

models.py
#-*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models



# Modulo de Negócio.

CHOICE_INFO_RESERVA = (
    ('aguradando', 'Aguardando analise'),
    ('nao-autorizado', 'Não autorizado'),
    ('cancelado', 'Cancelado'),
    ('autorizado', 'Autorizado'),
)

CHOICE_PAPEL_USUARIO = (
    ('gestor', 'Gestor'),
    ('solicitante', 'Solicitante')
)


class Localizacao(models.Model):
    """
    Class que abstrai a localização de espaços
    """
    nome = models.CharField(max_length=50)
    endereco = models.TextField()
    latitude = models.CharField(max_length=20, null=True, blank=True)
    longitude = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return self.nome


class Gestor(models.Model):
    """
    Classe de modelo que abstrai usuário(s) responsável pela gestão de seus
    espaços fisicos
    """
    papel = models.CharField(max_length=30, default='solicitante', choices=CHOICE_PAPEL_USUARIO)
    usuario = models.OneToOneField(User, related_name='papel', on_delete=models.CASCADE)


    def __str__(self):
        return self.usuario.get_full_name()


class CategoriaEspaco(models.Model):
    """
    Classe que abstai categorizador de tipo de espaço fisico para reserva
    """

    nome = models.CharField(max_length=50)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.nome


class Espaco(models.Model):
    """
    Class que abstrai os espaços físicos disponíveis para locação
    """

    nome = models.CharField(max_length=50)
    descricao = models.TextField(null=True, blank=True)
    gestor = models.ForeignKey(Gestor, on_delete=models.CASCADE)
    categoria = models.ForeignKey(CategoriaEspaco, on_delete=models.CASCADE)
    localizacao = models.ForeignKey(Localizacao, on_delete=models.CASCADE, related_name='espacos_deste')
    permiti_locacao = models.BooleanField(default=False)


    def __str__(self):
        return self.nome
    

class ItemEspaco(models.Model):
    """
    Class que abstrai os itens que compoem os espaços fisicos
    """

    espaco = models.ForeignKey(Espaco, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50)
    descricao = models.TextField(null=True, blank=True)
    observacao = models.TextField(null=True, blank=True)
    quantidade = models.PositiveIntegerField(default=0)
    status = models.BooleanField(default=True)


class Reserva(models.Model):
    """
    Class que abstrai os pedidos de reserva de espaços
    """

    descricao = models.TextField()
    data_pedido_at = models.DateTimeField(auto_created=True)
    solicitante = models.ForeignKey(User, on_delete=models.CASCADE, related_name='minhas_reservas')

    def __str__(self):
        from django.utils.html import format_html
        return format_html('Código da resevar <b>%s</b>, resgitrada em %s' % (self.id, self.data_pedido_at))


class ItemReserva(models.Model):
    """
    Tabela de itens da reserva
    """

    reserva = models.ForeignKey(Reserva, on_delete=True, related_name='dados_reserva')
    espaco = models.ForeignKey(Espaco, on_delete=True)
    inicio_at = models.DateTimeField()
    termino_at = models.DateTimeField()
    info_reserva = models.CharField(max_length=15, default='aguradando', choices=CHOICE_INFO_RESERVA)
    observacao = models.TextField(null=True, blank=True)
    status = models.BooleanField(default=False)

forms/categoria_forms.py
#-*- coding: utf-8 -*-

from django import forms

from space.models import CategoriaEspaco


class CategoriaEspacoForm(forms.ModelForm):

    class Meta:

        model = CategoriaEspaco
        
        fields = ['nome', 'status',]
        
        labels = {
            'nome': 'Nome da categoria',
            'status': 'Habilitado'
        }

        help_texts = {
            'nome': 'Descreva um nome para um grupo de categória. ex.: "Salas", "Auditórios", "Laboratório".',
        }

forms/espaco_forms.py
#-*- coding: utf-8 -*-

from django import forms
from space.models import Espaco

class EspacoCreateForm(forms.ModelForm):

    class Meta:
        model = Espaco
        fields = ['nome', 'descricao', 'categoria']
        labels = {
            'nome': 'Nome do espaço',
            'descricao': 'Descrição do espaço',
            'categoria': 'Categoria'
        }

        help_texts = {
            'categoria': 'Selecione uma categoria para o espaço físico.'
        }

forms/localizacao_forms.py
#-*- coding: utf-8 -*-
from django import forms

from space.models import Localizacao

class LocalizacaoForm(forms.ModelForm):

    class Meta:
        model = Localizacao
        fields = ['nome', 'endereco', 'latitude', 'longitude',]
        labels = {
            'nome': 'Identificador',
            'endereco': 'Endereço',
            'latitude': 'Latitude',
            'longitude': 'Longitude',
        }

forms/reserva_forms.py
#-*- coding: utf-8 -*-
from django import forms
from space.models import Reserva

class ReservaCreateForm(forms.ModelForm):

    #def __ini__(self, inicio_at=None, *args, **kwargs):
    #    super(AgendaCreateForm, self).__init__(*args, **kwargs)
    #    self.inicio_at[''] = inicio_at

    inicio_at = forms.DateTimeField(label='Início do evento.', required=True, )
    termino_at = forms.DateTimeField(label='Termino do evento.', required=True,)
    class Meta:
        model = Reserva
        fields = ['descricao']
        labels = {
            'descricao': 'Objetivo da reserva',
        }
        widgets = {
            'descricao': forms.Textarea(attrs={'rows': 3,})
        }

templates/space/pages/categorias.html
{% load bootstrap %}

{% block content %}
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">Categorias</h6>
        <div class="text-muted pt-3">
            {% if action == 'list' %}
                <p>
                    <a href="{% url 'space:manage-categoria' 'create' %}"><i class="fa fa-plus-circle"></i> Create</a>
                </p>
            {% endif %}
            {% if form %}
                <form action="" method="POST" class="col-12">
                    {% csrf_token %}
                    {{form|bootstrap}}
                    <input type="submit" value="Gravar" class="btn btn-success">
                    <a href="{% url 'space:categorias' %}" class="btn btn-warning">Fechar</a>
                    {% if object %}
                        <a href="{% url 'space:manage-categoria' object.id 'delete' %}" class="btn btn-danger">Excluir</a>
                    {% endif %}
                </form>
            {% else %}
                {% if objects %}
                    <ul>
                        {% for item in objects %}
                        <li><a href="{% url 'space:manage-categoria' item.id 'update' %}">{{item}}</a></li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/space/pages/espacos.html
{% load bootstrap %}

{% block content %}
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">Espaços Fisicos</h6>
        <div class="text-muted pt-3">
            {% if action == 'list' %}
                <p>
                    <a href="{% url 'space:espacos' %}?action=create"><i class="fa fa-plus-circle"></i> Create</a>
                </p>
            {% endif %}
            {% if form %}
                <form action="" method="POST" class="col-12">
                    {% csrf_token %}
                    {{form|bootstrap}}
                    <input type="submit" value="Gravar" class="btn btn-success">
                    <a href="{% url 'space:espacos' %}" class="btn btn-warning">Fechar</a>
                    {% if object %}
                        <a href="{% url 'space:espacos' object.id %}?action=delete" class="btn btn-danger">Excluir</a>
                    {% endif %}
                </form>
            {% else %}
                {% if objects %}
                    <ul>
                        {% for item in objects %}
                        <li>
                            <a href="{% url 'space:espacos' item.id %}?action=update&localizador={{item.localizacao.id}}">{{item}}</a>
                            &nbsp;->&nbsp;<span>{{item.localizacao}}</span>
                        </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/space/pages/gestores.html
{% load bootstrap %}

{% block content %}
<div id="show-pagina">
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">Usuários</h6>
        <div class="text-muted pt-3">
            {% if action == 'list' %}
                <span>
                    <a href="#" data-toggle="modal" class="nav-link"
                        data-target="#form-modal"
                        data-action="create"
                        data-titulo="Novo Gestor"
                        data-url='{% url 'space:manage-gestores' 'add_item' %}' >
                        <i class="fa fa-plus-circle"></i> Create</a>
                </span>
            {% endif %}
            {% if form %}
                <form action="" method="POST" class="col-12">
                    {% csrf_token %}
                    {{form|bootstrap}}
                    <input type="submit" value="Gravar" class="btn btn-success">
                    <a href="{% url 'space:gestores' %}" class="btn btn-warning">Fechar</a>
                    {% if object %}
                        <a href="{% url 'space:manage-gestores' object.id 'delete' %}" class="btn btn-danger">Excluir</a>
                    {% endif %}
                </form>
            {% else %}
                {% if objects %}
                    <ul>
                        {% for item in objects %}
                            <li><a href="{% url 'space:manage-gestores' item.id 'update' %}">{{item}}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>Nenhum objeto encontrado.</p>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/space/pages/localizacao.html
{% load bootstrap %}

{% block content %}
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">Localização</h6>
        <div class="text-muted pt-3">
            {% if action == 'list' %}
                <p>
                    <a href="{% url 'space:manage-localizador' %}?action=create"><i class="fa fa-plus-circle"></i> Create</a>
                </p>
            {% endif %}
            {% if form %}
                <form action="" method="POST" class="col-12">
                    {% csrf_token %}
                    {{form|bootstrap}}
                    <input type="submit" value="Gravar" class="btn btn-success">
                    <a href="{% url 'space:manage-localizador' %}" class="btn btn-warning">Fechar</a>
                    {% if object %}
                        <a href="{% url 'space:manage-localizador' object.id %}?action=delete" class="btn btn-danger">Excluir</a>
                    {% endif %}
                </form>
            {% else %}
                {% if objects %}
                    <ul>
                        {% for item in objects %}
                        <li>
                            <a href="{% url 'space:manage-localizador' item.id %}?action=update">{{item}}</a>&nbsp;
                            <a href="{% url 'space:manage-localizador' item.id %}?localizador=_">[ Add ]</a>
                        </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/space/pages/reservas.html
{% load bootstrap %}

{% block content %}
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">{{ titulo }}s</h6>
    <div class="text-muted pt-3">
        {% if action == 'list' %}
        <p>
            <a href="{% url 'space:manage-reservas' 'create' %}"><i class="fa fa-plus-circle"></i> Create</a>
        </p>
        {% endif %}
        {% if form %}
        <form action="" method="POST" class="col-12">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-8 col-sm-6">
                            {{form|bootstrap}}
                        </div>
                        <div class="col-4 col-sm-6">
                            {% if objects %}
                            <span class="text-success">Relação de espacos.</span>
                            <hr>
                            {% for item in objects %}
                            <p><input type="checkbox" name="espacos" value="{{item.id}}" /> {{item.nome}}.</p>
                            {% endfor %}
                            {% else %}
                            <p>Nenhum espaço disponível para reservar.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <input type="submit" value="Gravar" class="btn btn-success">
            <a href="{% url 'space:reservas' %}" class="btn btn-warning">Fechar</a>
            {% if object %}
            <a href="#" class="btn btn-danger">Excluir</a>
            {% endif %}
        </form>
        {% else %}
        <ul id="registros" style="list-style: none;">
            {% if objects %}
            {% for item in objects %}
            <li id="row_{{ item.id }}" style="padding: 10px 0 10px 0;">
                <a href="#collapse_{{ item.id }}" class="btn-success btn-sm" data-toggle="collapse" title="{{item.descricao}}"
                aria-controls="collapse_{{ item.id }}">?</a>&nbsp;
                Código da reserva <strong>{{item.id}}</strong>, registrado em {{ item.data_pedido_at }}.
            </li>
            <div class="collapse" id="collapse_{{ item.id }}">
                <div class="card card-body">
                    {{ item.descricao }}, <a href="#">A. S</a>&nbsp;<a href="#">D. S</a>
                    <ul>
                    {% with reservas=item.dados_reserva.all %}
                    {% for i in reservas %}
                        <li><strong>{{i.espaco.nome}}</strong>.<br>
                            Período: de {{ i.inicio_at|date:'d/m/Y' }} <strong>até</strong> {{ i.termino_at|date:'d/m/Y' }}<br>
                            Status: {{ i.get_info_reserva_display }}
                        </li>
                    {% endfor %}
                    {% endwith %}
                    </ul>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <li>Nenhum reserva registrada.</li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
</div>

{% endblock content %}